Repository klaviyo/klaviyo-swift-sdk, pull requests merged in 2024-01, with the labels that each got.

#134 remove initializer for setting identifiers in events
  Sources/KlaviyoSwift/KlaviyoModels.swift
Labels: evergreen, minor-release

#133 Remove deprecated api and associated code.
  Sources/KlaviyoSwift/InternalAPIModels.swift
  Sources/KlaviyoSwift/Klaviyo.swift
  Sources/KlaviyoSwift/KlaviyoState.swift
  Sources/KlaviyoSwift/StateManagement.swift
  Tests/KlaviyoSwiftTests/KlaviyoStateTests.swift
  Tests/KlaviyoSwiftTests/LegacyTests.swift
  Tests/KlaviyoSwiftTests/TestData.swift
  Tests/KlaviyoSwiftTests/Tests.swift
Labels: evergreen, major-release

#139 Breaking changes to remove old event metric cases
  MIGRATION_GUIDE.md
  Sources/KlaviyoSwift/KlaviyoModels.swift
Labels: major-release
